spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 52719056470-3i9e7sbcprnqifguq3anarlkvj6q2s6e.apps.googleusercontent.com
            client-secret: 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